//this file is autogenerated by strongly-type script, any manual changes will be overriden on next build
namespace BlazorServerJsInterOp.MyLib
{
    public static class MyLib 
    {
        public static string FileName => "my_lib.js";
        public static string LibraryName => "MyLib";
        
        public static class Methods
        {
            public static string GetCurrentTime = "GetCurrentTime";
			public static string GetToday = "GetToday";
			public static string InitializeMap = "InitializeMap";
        }
    }
}
