//this file is autogenerated by strongly-type script, any manual changes will be overriden on next build
namespace BlazorServerJsInterOp.JsLib
{
    public static class JsLib 
    {
        public static string GetCurrentTime = "MyLib.GetCurrentTime";
		public static string GetToday = "MyLib.GetToday";
		public static string InitializeMap = "MyLib.InitializeMap";
    }
}
